services:

  userservice:
    build: ./userservice
    container_name: userservice
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  authservice:
    build: ./authservice
    container_name: authservice
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - auth-db

  orderservice:
    build: ./orderservice
    container_name: orderservice
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - order-db

  db:
    image: postgres:16
    container_name: userservice_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userservice
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16
    container_name: authservice_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authservice
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: orderservice_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderservice
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: userservice_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
  auth_db_data:
  order_db_data: