spring.application.name=api-gateway

jwt.secret=${JWT_SECRET:auth-secret-key-for-json-web-token-service-123456}

security.paths=/authservice/auth/login,\
  /authservice/auth/register,\
  /authservice/v3/api-docs,\
  /userservice/v3/api-docs,\
  /orderservice/v3/api-docs,\
  /paymentservice/v3/api-docs,\
  /v3/api-docs/**,/swagger-ui/**,\
  /swagger-ui.html