spring.application.name=paymentservice

spring.mongodb.uri=mongodb://payment-mongodb:27017/paymentdb
#spring.data.mongodb.uri=mongodb://payment-mongodb:27017/paymentdb?connectTimeoutMS=30000&serverSelectionTimeoutMS=30000

#spring.data.mongodb.host=payment-mongodb
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=paymentdb

external.api.url=${EXTERNAL_API_URL:https://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1}

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.forward-headers-strategy=framework